package org.romainlavabre.financetracker.configuration.response;

/**
 * @author Romain Lavabre <romainlavabre98@gmail.com>
 */
public interface Message {
    String EXCHANGE_TRADED_FUND_PUBLIC_NAME_REQUIRED            = "EXCHANGE_TRADED_FUND_PUBLIC_NAME_REQUIRED";
    String EXCHANGE_TRADED_FUND_PAGE_LINK_REQUIRED              = "EXCHANGE_TRADED_FUND_PAGE_LINK_REQUIRED";
    String EXCHANGE_TRADED_FUND_AUTOMATION_NOT_SUPPORT_PROVIDER = "EXCHANGE_TRADED_FUND_AUTOMATION_NOT_SUPPORT_PROVIDER";
    String EXCHANGE_TRADED_FUND_PRODUCT_ID_REQUIRED             = "EXCHANGE_TRADED_FUND_PRODUCT_ID_REQUIRED";
    String EXCHANGE_TRADED_FUND_PRICING_REQUIRED                = "EXCHANGE_TRADED_FUND_PRICING_REQUIRED";
    String UNABLE_TO_BUILD_EXCHANGE_TRADED_FUND                 = "UNABLE_TO_BUILD_EXCHANGE_TRADED_FUND";
    String EXCHANGE_TRADED_FUND_RISK_REQUIRED                   = "EXCHANGE_TRADED_FUND_RISK_REQUIRED";
    String EXCHANGE_TRADED_FUND_PROVIDER_REQUIRED               = "EXCHANGE_TRADED_FUND_PROVIDER_REQUIRED";
    String EXCHANGE_TRADED_FUND_AMOUNT_REQUIRED                 = "EXCHANGE_TRADED_FUND_AMOUNT_REQUIRED";
    String ANNUALLY_YIELD_YEAR_REQUIRED                         = "ANNUALLY_YIELD_YEAR_REQUIRED";
    String ANNUALLY_YIELD_YIELD_REQUIRED                        = "ANNUALLY_YIELD_YIELD_REQUIRED";
    String ANNUALLY_YIELD_ALREADY_EXISTS                        = "ANNUALLY_YIELD_ALREADY_EXISTS";
    String COUNTRY_NAME_REQUIRED                                = "COUNTRY_NAME_REQUIRED";
    String COUNTRY_CONTINENT_REQUIRED                           = "COUNTRY_CONTINENT_REQUIRED";
}
